spring:
  application:
    name: registry-core

registry:
  serverlist:
    - http://localhost:8484
    - http://localhost:8485
    - http://localhost:8486

logging:
  level:
    root: error
    cn.ipman.registry: debug